version: "3.7"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.12.1"
    environment:
      discovery.type: "single-node"
      cluster.name: "cluster-1"
      node.name: "node-1"
    ports:
      - "9200:9200"

#  elastichq:
#    image: "elastichq/elasticsearch-hq"
#    ports:
#      - "5000:5000"
#    depends_on:
#      - "elasticsearch"
