apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingester.fullname" . }}
  labels:
    {{- include "ingester.labels" . | nindent 4 }}
data:
  ELASTICSEARCH_ADDRESSES: "http://elasticsearch-master.elastic-system.svc.cluster.local:9200"
