apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingester.fullname" . }}
  labels:
    {{- include "ingester.labels" . | nindent 4 }}
data:
  ELASTICSEARCH_USERNAME: {{ .Values.elastic.username  }}
  ELASTICSEARCH_PASSWORD: {{ .Values.elastic.password  }}
type: Opaque